config/routes.rb
Rails.application.routes.draw do

  resources :rg
  resources :users
  resources :sessions
  resources :tournois

  root 'rg#homepage'

  get 'bracketrg', to: 'rg#rg'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  get 'login',   to: 'sessions#new'
  post 'login',   to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'
  #get 'user', to: 'users#index'

  get '/malesingle', to: 'tournois#malesingle'
  post '/malesingle', to: 'tournois#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tournoi.rb
class Tournoi < ApplicationRecord
  serialize :payload, JSON
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: true, length: { maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 250 },
                    format: {with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
#Returns the hash (table) digest of the given string(password)
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                              BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def confirm!
    update!(confirmed_at: DateTime.now)
  end

  def confirmed?
    !! confirmed_at
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

#Returns true if the token matches the digest (token /matches password of user)
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

#Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#protect_from_forgery with: :exception
#protect_from_forgery with: :null_session
  include SessionsHelper
end

app/controllers/bracket_testing_controller.rb
class BracketTestingController < ApplicationController
end

app/controllers/rg_controller.rb
class RgController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
      # Log the user in and redirect to the user's profile/show page
      # Solely if both informations match
    else
      # Create error message if the params do not match the data base
      flash.now[:danger] = 'Invalid email/password or combination' #Try again
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to  root_url
  end
end

app/controllers/tournois_controller.rb
class TournoisController < ApplicationController
  def new
    @tournoi = Tournoi.new
  end

  def create

     @tournoi = Tournoi.new(payload: JSON.parse(params[:payload]))
    if @tournoi.save
      redirect_to root_url
        flash[:success] = "Your tournament bracket has been validated!"
      else
        redirect_to malesingle_url
      end
  end
  private
    # Never trust parameters from the scary internet
    def tournoi_params
      params.require(:tournoi).permit(:payload)
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
   before_action :admin_user,     only: [:destroy, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user =User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        log_in @user
        #format.json { render :show, status: :created, location: @user }
        flash[:success] = "Welcome to the Roland-Garros Tournament Bracket!"
        redirect_to @user
      else
        render 'new'
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    #respond_to do |format|
      if @user.update_attributes(user_params)
          flash[:success] = "Your Profile has been Updated"
          redirect_to @user
        #format.html { redirect_to @user, notice: 'User was successfully updated.' }
        #format.json { render :show, status: :ok, location: @user }
      else
        render 'edit'
        #format.html { render :edit }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    #end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
    flash[:success] = "Account has been successfully deleted"
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :lastname, :firstname, :address, :username)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
     @user = User.find(params[:id])
     redirect_to(root_url) unless @user == current_user
   end
   # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bracket_testing_helper.rb
module BracketTestingHelper
end

app/helpers/rg_helper.rb
module RgHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #User Logs in
    def log_in(user)
      session[:user_id] = user.id
    end

  #Remembers a user in a persistent session (user that usually logs in on th same computer on a regular basis)
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    # Returns true if the given user is the current user.
     def current_user?(user)
       user == current_user
     end

    # Display the current logged-in user if there is any / user correcponding to the remember token cookie
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: session[:user_id])
      elsif (user_id = cookies.signed[:user_id])
        #raise #beug sur le controller avec login param ligne 27
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

    #Display true if the user is logged in, false otherwise

      def logged_in?
        !current_user.nil?
      end

      def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
      end

      #Logs out the current user method
      def log_out
        session.delete(:user_id)
        @current_user = nil
      end
      # Redirects to stored location (or to the default).
    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end

    # Stores the URL trying to be accessed.
    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/tournois_helper.rb
module TournoisHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/layouts/_footer.hmtl.erb
<div class="page wraper">








</div>

app/views/layouts/_header.html.erb
<nav>
  <div>
    <h1>
      <a>
       <%= link_to image_tag("rg.png", :size => "120x120"), :class => ''%>
      </a>
    </h1>
  </div>
  <h2 class="tournois">TOURNAMENT-BRACKETS</h2>
  <ul class="button">
    <li class="login"><%= link_to "Login", login_path %></li>
    <li class="signup"><%= link_to "Sign up!", signup_path %></li>
  </ul>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar-custom">
<!--
 <%= link_to image_tag("rg.png", :border=>0), :class => 'rg-logo', :size => "150"%>
-->
  <%= link_to "Tournament Bracket", root_path, :class => "logo-title" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


 <!-- Tournois boutton
  <ul class="nav nav-tabs">
    <li class="nav-item dropdown show">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">Tournois</a>
      <div class="dropdown-menu show" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 34px, 0px); top: 0px; left: 0px; will-change: transform;">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Separated link</a>
      </div>
    </li>
  </ul>

-->
  <!-- Bracket boutton -->

  <!-- Sign-up + Login -->
  <% if logged_in? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li><%= link_to "Users", users_path %></li>
      <li class="divider"></li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete %>
      </li>
    </ul>
  </li>

<% else %>
<!--
  <ul class="navbar-nav ml-auto">
         <li class="nav-item dropdown show">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">
        <i class="fa fa-fw fa-lock"></i>Login
      </a>
      <div class="dropdown-menu dropdown-size-280">
        <form>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon">
                <i class="fa fa-user"></i>
              </span>
              <input type="text" class="form-control" placeholder="Username">
            </div>
          </div>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon">
                <i class="fa fa-shield"></i>
              </span>
              <input type="password" class="form-control" placeholder="Password">
            </div>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary">Login
              <i class="fa fa-sign-in"></i>
            </button>
          </div>
        </form>
      </div>
    </li>
  </ul>
  -->
  <%= link_to "Login", login_path, :class => "btn btn-danger navbar-btn"%>
  <!-- Sign up -->
  <%= link_to "Sign Up", signup_path, :class => "btn btn-danger navbar-btn"%>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bracket</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="go-debug.js"></script>
  <!-- "Tournament/Bracket JS lib -->
  <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
  <!-- Client/server  data management-->
    <meta name="viewport" content-type="width=device-width initial-scale=1">
<!--    Google fonts--->
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Cardo|Gloria+Hallelujah|Shrikhand" rel="stylesheet">
  </head>

  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/rg/homepage.html.erb
<script>
  function init() {

    var $ = go.GraphObject.make;  // for conciseness in defining templates

    myDiagram =
      $(go.Diagram, "myDiagramDiv",  // create a Diagram for the DIV HTML element
        {
          initialContentAlignment: go.Spot.Center,  // center the content
          "textEditingTool.starting": go.TextEditingTool.SingleClick,
          "textEditingTool.textValidation": isValidScore,
          layout: $(go.TreeLayout, { angle: 180 }),
          "undoManager.isEnabled": true
        });

    // validation function for editing text
    function isValidScore(textblock, oldstr, newstr) {
      if (newstr === "") return true;
      var num = parseInt(newstr, 10);
      return !isNaN(num) && num >= 0 && num <= 1;
    }

    // define a simple Node template
    myDiagram.nodeTemplate =
      $(go.Node, "Auto",
        { selectable: false },
        $(go.Shape, "Rectangle",
          { fill: '#8C8C8C', stroke: null },
          // Shape.fill is bound to Node.data.color
          new go.Binding("fill", "color")),
        $(go.Panel, "Table",
          $(go.RowColumnDefinition, { column: 0, separatorStroke: "black" }),
          $(go.RowColumnDefinition, { column: 1, separatorStroke: "black", background: "#BABABA" }),
          $(go.RowColumnDefinition, { row: 0, separatorStroke: "black" }),
          $(go.RowColumnDefinition, { row: 1, separatorStroke: "black" }),
          $(go.TextBlock, "",
            { row: 0,
              wrap: go.TextBlock.None, margin: 5, width: 90,
              isMultiline: false, textAlign: 'left',
              font: '10pt  Segoe UI,sans-serif', stroke: 'white' },
            new go.Binding("text", "player1").makeTwoWay()),
          $(go.TextBlock, "",
            { row: 1,
              wrap: go.TextBlock.None, margin: 5, width: 90,
              isMultiline: false, textAlign: 'left',
              font: '10pt  Segoe UI,sans-serif', stroke: 'white' },
            new go.Binding("text", "player2").makeTwoWay()),
          $(go.TextBlock, "",
            { column: 1, row: 0,
              wrap: go.TextBlock.None, margin: 2, width: 25,
              isMultiline: false, editable: true, textAlign: 'center',
              font: '10pt  Segoe UI,sans-serif', stroke: 'black' },
            new go.Binding("text", "score1").makeTwoWay()),
          $(go.TextBlock, "",
            { column: 1, row: 1,
              wrap: go.TextBlock.None, margin: 2, width: 25,
              isMultiline: false, editable: true, textAlign: 'center',
              font: '10pt  Segoe UI,sans-serif', stroke: 'black' },
            new go.Binding("text", "score2").makeTwoWay())
        )
      );

    // define the Link template
    myDiagram.linkTemplate =
      $(go.Link,
        { routing: go.Link.Orthogonal,
          selectable: false },
        $(go.Shape, { strokeWidth: 2, stroke: 'white' }));


    // Generates the original graph from an array of player names
    function createPairs(players) {
      if (players.length % 2 !== 0) players.push('(empty)');
      var startingGroups = players.length / 2;
      var currentLevel = Math.ceil(Math.log(startingGroups) / Math.log(2));
      var levelGroups = [];
      var currentLevel = Math.ceil(Math.log(startingGroups) / Math.log(2));
      for (var i = 0; i < startingGroups; i++) {
        levelGroups.push(currentLevel + '-' + i);
      }
      var totalGroups = [];
      makeLevel(levelGroups, currentLevel, totalGroups, players);
      return totalGroups;
    }

    function makeLevel(levelGroups, currentLevel, totalGroups, players) {
      currentLevel--;
      var len = levelGroups.length;
      var parentKeys = [];
      var parentNumber = 0;
      var p = '';
      for (var i = 0; i < len; i++) {
        if (parentNumber === 0) {
          p = currentLevel + '-' + parentKeys.length;
          parentKeys.push(p);
        }

        if (players !== null) {
          var p1 = players[i*2];
          var p2 = players[(i*2) + 1];
          totalGroups.push({
            key: levelGroups[i], parent: p, player1: p1, player2: p2, parentNumber: parentNumber
          });
        } else {
          totalGroups.push({ key: levelGroups[i], parent: p, parentNumber: parentNumber });
        }

        parentNumber++;
        if (parentNumber > 1) parentNumber = 0;
      }

      // after the first created level there are no player names
      if (currentLevel >= 0) makeLevel(parentKeys, currentLevel, totalGroups, null)
    }

    function makeModel(players) {
      var model = new go.TreeModel(createPairs(players));

      model.addChangedListener(function(e) {
        if (e.propertyName !== 'score1' && e.propertyName !== 'score2') return;
        var data = e.object;
        if (isNaN(data.score1) || isNaN(data.score2)) return;

        // TODO: What happens if score1 and score2 are the same number?

        // both score1 and score2 are numbers,
        // set the name of the higher-score'd player in the advancing (parent) node
        // if the data.parentNumber is 0, then we set player1 on the parent
        // if the data.parentNumber is 1, then we set player2
        var parent = myDiagram.findNodeForKey(data.parent);
        if (parent === null) return;

        var playerName = parseInt(data.score1) > parseInt(data.score2) ? data.player1 : data.player2;
        if (parseInt(data.score1) === parseInt(data.score2)) playerName = "";
        myDiagram.model.setDataProperty(parent.data, (data.parentNumber === 0 ? "player1" : "player2"), playerName);
      });

      myDiagram.model = model;
    }

  makeModel(['MURRAY',
             'KHACHANOV',
             'VERDASCO',
             'NISHIKORI',
             'WAWRINKA',
             'MONFILS',
             'ANDERSON',
             'CILIC',
             'RAONIC',
             'CARRENO',
             'BAUTISTA',
             'NADAL',
             'THIEM',
             'ZEBALLOS',
             'RAMOS',
             'DJOKOVIC',
              ]);
               // define the Link template
  myDiagram.linkTemplate =
    $(go.Link, go.Link.Orthogonal,
      { corner: 5, relinkableFrom: true, relinkableTo: true },
        $(go.Shape, { strokeWidth: 4, stroke:
           "#d5622a" }));  // the link shape
                   // read in the JSON-format data from the "mySavedModel" element

                   // support editing the properties of the selected person in HTML
      }
      // Show the diagram's model in JSON format
    function save() {
    var tojs = myDiagram.model.toJSON();
    parsed_bracket = JSON.parse(tojs);
    stringify_tojs = JSON.stringify(parsed_bracket);
     myDiagram.isModified = false;
                   }
    function load() {
      myDiagram.model = go.Model.fromJson(parsed_bracket);
      myDiagram.isReadOnly = true;
    }

   // end init
// function callback () {
//console.log(this.responseText);
//};

      // var request = new XMLHttpRequest();
      //  request.onload = callback;
      //  request.open("post", "http://localhost:3000/request");
      //  var formData = new FormData();
        //formData.append('bracket', 'ticket')
        //request.send(formData);

      //    var settings = { bracket: bracket}
      //    $.ajax({
      //        url: 'tickets/new',
          //    type: 'POST',
          //    dataType: 'json',
          //    data: settings,
          //    cache: true
          //      });

</script>



<body onload="init()">
  <div id="myDiagramDiv" style="border: solid 1px black; background: #4D4D4D; width:700px; height:600px"></div>

    <button id="SaveButton" onclick="save()">Save</button>



  <button onclick="load()">Load</button>
</div>
</body>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :firstname %>
  <%= f.text_field :firstname, class: 'form-control' %>

  <%= f.label :lastname %>
  <%= f.text_field :lastname, class: 'form-control' %>


  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th>Confirmed at</th>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Address</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.confirmed_at %></td>
        <td><%= user.lastname %></td>
        <td><%= user.firstname %></td>
        <td><%= user.address %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
 <% provide(:button_text, 'Create my account') %>

<!--<div id="login-box">
  <div class="left">
-->
<h1>Sign up</h1>
<!--
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :firstname %>
  <%= f.text_field :firstname, class: 'form-control' %>

  <%= f.label :lastname %>
  <%= f.text_field :lastname, class: 'form-control' %>


  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
</div>
<div class="right">
    <span class="loginwith">Sign in with<br />social network</span>

    <button class="social-signin facebook">Log in with facebook</button>
    <button class="social-signin twitter">Log in with Twitter</button>
    <button class="social-signin google">Log in with Google+</button>
  </div>
  <div class="or">OR</div>
</div>




-->

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
    </section>
  </aside>
</div>